name: AI Content Processing

on:
  push:
    branches: [ main, master ]
    paths: 
      - '**/*.md'
  workflow_dispatch:

jobs:
  process-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      models: read
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: '**/*.md'
        files_ignore: '**/*_processed.md'
        separator: 'newline'

    - name: Debug workflow context
      run: |
        echo "=== Workflow Debug Info ==="
        echo "Event name: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Repository: ${{ github.repository }}"
        echo "Changed files from action: '${{ steps.changed-files.outputs.all_changed_files }}'"
        echo "Changed files count: '${{ steps.changed-files.outputs.all_changed_files_count }}'"
        echo "=== File System Debug ==="
        echo "Current directory:"
        pwd
        echo "All markdown files in repo:"
        find . -name "*.md" -type f | head -20
        echo "Recent commits:"
        git log --oneline -5
        echo "Git status:"
        git status --porcelain

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-cache-dir

    - name: Run AI processing script
      id: ai-process
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        python .github/scripts/ai_processor.py

    - name: Commit and push results
      if: steps.ai-process.outputs.processed_files != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROCESSED_FILES: ${{ steps.ai-process.outputs.processed_files }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Add each processed file individually
        echo "$PROCESSED_FILES" | tr ',' '\n' | while read -r file; do
          if [ -n "$file" ]; then
            git add "$file"
            echo "Added file: $file"
          fi
        done
        if git diff --staged --quiet; then
          echo "No new processed files to commit"
        else
          git commit -m "AI-processed content"
          git push
          echo "Processed files committed and pushed"
        fi